import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Check, ChevronDown, ChevronUp, Clock3, ExternalLink, FileText, Globe2, Image as ImageIcon, LayoutDashboard, LogOut, Menu, Monitor, PanelLeftClose, Plus, RefreshCw, Save, Search, Send, Settings2, Smartphone, Tablet, Trash2, Upload, Users, X } from 'lucide-react';
import { adminApi, CmsDocument, CmsDocumentSummary, Enquiry, MediaItem } from './api';
import { CMS_SCHEMAS, DocumentSchema, FieldSchema, hydrateCmsDocument, RepeaterSchema, SectionSchema } from './schema';
import { CORE_SERVICES, PORTFOLIO_CATEGORIES, PORTFOLIO_ITEMS } from '../data/content';
import type { PortfolioItem, ServiceItem } from '../types';
import './admin.css';

type AdminUser = { username: string; role: string };
type Screen = 'dashboard' | 'content' | 'media' | 'enquiries';
type Device = 'desktop' | 'tablet' | 'mobile';

const clone = <T,>(value: T): T => structuredClone(value);
const parts = (path: string) => path.split('.').filter(Boolean);
function getValue(root: unknown, path: string): unknown {
  return parts(path).reduce<unknown>((value, key) => value && typeof value === 'object' ? (value as Record<string, unknown>)[key] : undefined, root);
}
function setValue(root: Record<string, unknown>, path: string, value: unknown): Record<string, unknown> {
  const next = clone(root); let cursor: Record<string, unknown> = next; const keys = parts(path);
  keys.forEach((key, index) => { if (index === keys.length - 1) cursor[key] = value; else { const child = cursor[key]; cursor[key] = child && typeof child === 'object' && !Array.isArray(child) ? clone(child as Record<string, unknown>) : {}; cursor = cursor[key] as Record<string, unknown>; } });
  return next;
}
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not published yet';
const announcePublishedContent = (key: string) => {
  const message = { type: 'published', key, at: Date.now() };
  localStorage.setItem('joozz-content-published', JSON.stringify(message));
  if (typeof BroadcastChannel !== 'undefined') { const channel = new BroadcastChannel('joozz-content'); channel.postMessage(message); channel.close(); }
};

export default function AdminApp() {
  const [user, setUser] = useState<AdminUser | null>(null);
  const [checking, setChecking] = useState(true);
  useEffect(() => { adminApi.session().then(setUser).catch(() => setUser(null)).finally(() => setChecking(false)); }, []);
  if (checking) return <div className="cms-boot"><span className="cms-spinner" />Opening your studio…</div>;
  if (!user) return <Login onLogin={setUser} />;
  return <CmsShell user={user} onLogout={() => { adminApi.logout().finally(() => setUser(null)); }} />;
}

function Login({ onLogin }: { onLogin: (user: AdminUser) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { onLogin(await adminApi.login(String(form.get('username') || ''), String(form.get('password') || ''))); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to sign in.'); } finally { setBusy(false); } };
  return <main className="cms-login-page"><section className="cms-login-card"><div className="cms-login-mark">J</div><p className="cms-kicker">JOOZZ CONTENT ATELIER</p><h1>Welcome back.</h1><p>Sign in to manage your website content, media and enquiries.</p><form onSubmit={submit}><label>Username<input name="username" autoComplete="username" required autoFocus /></label><label>Password<input name="password" type="password" autoComplete="current-password" required /></label>{error && <div className="cms-error" role="alert">{error}</div>}<button className="cms-primary" disabled={busy}>{busy ? <><span className="cms-spinner" />Signing in…</> : 'Sign in securely'}</button></form></section></main>;
}

function CmsShell({ user, onLogout }: { user: AdminUser; onLogout: () => void }) {
  const initialPath = window.location.pathname.split('/').filter(Boolean); const initialKey = initialPath[0] === 'admin' && initialPath[1] === 'content' ? initialPath[2] || null : null;
  const initialScreen: Screen = initialKey ? 'content' : initialPath[1] === 'media' ? 'media' : initialPath[1] === 'enquiries' ? 'enquiries' : initialPath[1] === 'content' ? 'content' : 'dashboard';
  const [screen, setScreen] = useState<Screen>(initialScreen); const [documents, setDocuments] = useState<CmsDocumentSummary[]>([]); const [portfolioItems, setPortfolioItems] = useState<PortfolioItem[]>(PORTFOLIO_ITEMS); const [serviceItems, setServiceItems] = useState<ServiceItem[]>(CORE_SERVICES); const [selectedKey, setSelectedKey] = useState<string | null>(initialKey); const [mobileNav, setMobileNav] = useState(false); const [search, setSearch] = useState(''); const [openGroups, setOpenGroups] = useState({ content: true, global: true, manage: true });
  const refreshDocuments = useCallback(() => adminApi.documents().then(({ items }) => setDocuments(items)), []);
  useEffect(() => { refreshDocuments(); }, [refreshDocuments]);
  useEffect(() => { adminApi.document('portfolio').then((document) => { const items = document.draft.items; if (Array.isArray(items)) setPortfolioItems(items as PortfolioItem[]); }).catch(() => undefined); }, []);
  useEffect(() => { adminApi.document('services').then((document) => { const items = document.draft.items; if (Array.isArray(items)) setServiceItems(items as ServiceItem[]); }).catch(() => undefined); }, []);
  useEffect(() => { if (selectedKey !== 'home') return; adminApi.document('services').then((document) => { const items = document.draft.items; if (Array.isArray(items)) setServiceItems(items as ServiceItem[]); }).catch(() => undefined); }, [selectedKey]);
  const openDocument = (key: string) => { window.history.pushState({}, '', `/admin/content/${key}`); setSelectedKey(key); setScreen('content'); setMobileNav(false); };
  const navigate = (next: Screen) => { window.history.pushState({}, '', next === 'dashboard' ? '/admin' : `/admin/${next}`); setScreen(next); setSelectedKey(null); setMobileNav(false); };
  useEffect(() => { const restorePath = () => { const path = window.location.pathname.split('/').filter(Boolean); const key = path[1] === 'content' ? path[2] || null : null; setSelectedKey(key); setScreen(key || path[1] === 'content' ? 'content' : path[1] === 'media' ? 'media' : path[1] === 'enquiries' ? 'enquiries' : 'dashboard'); }; window.addEventListener('popstate', restorePath); return () => window.removeEventListener('popstate', restorePath); }, []);
  const matches = documents.filter((document) => `${document.title} ${document.description}`.toLowerCase().includes(search.toLowerCase()));
  const toggleGroup = (group: keyof typeof openGroups) => setOpenGroups((current) => ({ ...current, [group]: !current[group] }));
  const currentTitle = selectedKey ? documents.find((item) => item.key === selectedKey)?.title || 'Page Editor' : screen === 'dashboard' ? 'Dashboard' : screen === 'content' ? 'Website Content' : screen === 'media' ? 'Media Library' : 'Enquiries';
  return <div className="cms-shell">
    <aside className={`cms-sidebar ${mobileNav ? 'is-open' : ''}`}>
      <div className="cms-brand"><div className="cms-brand-mark">J</div><div><strong>Joozz Studio</strong><span>Content Management</span></div><button className="cms-mobile-close" onClick={() => setMobileNav(false)}><X /></button></div>
      <div className="cms-search"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search website content…" /></div>
      <nav aria-label="Admin navigation">
        <button className={screen === 'dashboard' ? 'active' : ''} onClick={() => navigate('dashboard')}><LayoutDashboard />Dashboard</button>
        <button className="cms-nav-group" onClick={() => toggleGroup('content')} aria-expanded={openGroups.content}><span>Website Content</span><ChevronDown /></button>
        {openGroups.content && <div className="cms-nav-group-items">{matches.filter((item) => item.key !== 'global').map((item) => <button key={item.key} className={selectedKey === item.key ? 'active' : ''} onClick={() => openDocument(item.key)}><FileText />{item.title}{item.status === 'draft' && <i />}</button>)}</div>}
        <button className="cms-nav-group" onClick={() => toggleGroup('global')} aria-expanded={openGroups.global}><span>Global Content</span><ChevronDown /></button>
        {openGroups.global && <div className="cms-nav-group-items">{documents.filter((item) => item.key === 'global').map((item) => <button key={item.key} className={selectedKey === item.key ? 'active' : ''} onClick={() => openDocument(item.key)}><Globe2 />{item.title}{item.status === 'draft' && <i />}</button>)}</div>}
        <button className="cms-nav-group" onClick={() => toggleGroup('manage')} aria-expanded={openGroups.manage}><span>Manage</span><ChevronDown /></button>
        {openGroups.manage && <div className="cms-nav-group-items"><button className={screen === 'media' ? 'active' : ''} onClick={() => navigate('media')}><ImageIcon />Media Library</button><button className={screen === 'enquiries' ? 'active' : ''} onClick={() => navigate('enquiries')}><Send />Enquiries</button></div>}
      </nav>
      <a className="cms-sidebar-site-link" href="/" target="_blank" rel="noreferrer"><ExternalLink /><span><strong>View website</strong><small>Open the published site</small></span></a>
      <div className="cms-user"><span className="cms-user-avatar">{user.username.slice(0, 1).toUpperCase()}</span><div><strong>{user.username}</strong><span>{user.role}</span></div><button onClick={onLogout} title="Sign out" aria-label="Sign out"><LogOut /></button></div>
    </aside>
    {mobileNav && <button className="cms-sidebar-scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}
    <main className="cms-main"><header className="cms-topbar"><div><button className="cms-menu-trigger" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><span><small>Joozz Content Studio</small><strong>{currentTitle}</strong></span></div><div><span className="cms-live-indicator"><i />Website live</span><a href="/" target="_blank" rel="noreferrer" className="cms-topbar-link"><ExternalLink />View website</a></div></header>
      {screen === 'dashboard' && <Dashboard documents={documents} openDocument={openDocument} openMedia={() => navigate('media')} openEnquiries={() => navigate('enquiries')} />}
      {screen === 'content' && selectedKey && <PageEditor key={selectedKey} documentKey={selectedKey} availablePortfolio={portfolioItems} availableServices={serviceItems} onBack={() => navigate('content')} onRefresh={refreshDocuments} />}
      {screen === 'content' && !selectedKey && <ContentOverview documents={documents} openDocument={openDocument} />}
      {screen === 'media' && <MediaLibrary />}
      {screen === 'enquiries' && <Enquiries />}
    </main>
  </div>;
}

function Dashboard({ documents, openDocument, openMedia, openEnquiries }: { documents: CmsDocumentSummary[]; openDocument: (key: string) => void; openMedia: () => void; openEnquiries: () => void }) {
  const drafts = documents.filter((item) => item.status === 'draft').length;
  return <div className="cms-page cms-dashboard"><div className="cms-page-heading"><p className="cms-kicker">WEBSITE CONTROL CENTRE</p><h1>Your website,<br /><em>beautifully managed.</em></h1><p>Choose a page, edit one clear section at a time, preview it live and publish when you are ready.</p></div>
    <div className="cms-metrics"><article><strong>{documents.length}</strong><span>Managed areas</span></article><article><strong>{drafts}</strong><span>Drafts pending</span></article><article><strong>Live</strong><span>Website status</span></article></div>
    {drafts > 0 && <div className="cms-notice"><Clock3 /><div><strong>{drafts} draft{drafts === 1 ? '' : 's'} waiting</strong><span>Your live website is unchanged until you publish.</span></div></div>}
    <section><div className="cms-section-title"><div><p className="cms-kicker">QUICK ACTIONS</p><h2>Website content</h2></div></div><div className="cms-page-grid">{documents.map((document) => <button className="cms-page-card" key={document.key} onClick={() => openDocument(document.key)}><div className="cms-page-icon">{document.key === 'global' ? <Globe2 /> : <FileText />}</div><div><strong>{document.title}</strong><p>{document.description}</p><span className={document.status === 'draft' ? 'draft' : 'published'}>{document.status === 'draft' ? 'Draft changes' : 'Published'}</span></div><ExternalLink /></button>)}</div></section>
    <div className="cms-quick-row"><button onClick={openMedia}><ImageIcon /><span><strong>Media Library</strong><small>Upload and reuse images</small></span></button><button onClick={openEnquiries}><Send /><span><strong>Enquiries</strong><small>Review project requests</small></span></button></div>
  </div>;
}

function ContentOverview({ documents, openDocument }: { documents: CmsDocumentSummary[]; openDocument: (key: string) => void }) {
  return <div className="cms-page"><div className="cms-page-heading"><p className="cms-kicker">WEBSITE CONTENT</p><h1>Choose a page</h1><p>Each page is organised into the same sections visitors see on your website.</p></div><div className="cms-page-grid">{documents.map((item) => <button className="cms-page-card" onClick={() => openDocument(item.key)} key={item.key}><FileText /><div><strong>{item.title}</strong><p>{item.description}</p></div></button>)}</div></div>;
}

function PageEditor({ documentKey, availablePortfolio, availableServices, onBack, onRefresh }: { documentKey: string; availablePortfolio: PortfolioItem[]; availableServices: ServiceItem[]; onBack: () => void; onRefresh: () => void }) {
  const schema = CMS_SCHEMAS[documentKey]; const [record, setRecord] = useState<CmsDocument | null>(null); const [draft, setDraft] = useState<Record<string, unknown>>({}); const [activeSection, setActiveSection] = useState<string | null>(() => window.location.pathname.split('/').filter(Boolean)[3] || null); const [device, setDevice] = useState<Device>('desktop'); const [dirty, setDirty] = useState(false); const [saveState, setSaveState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle'); const [toast, setToast] = useState(''); const [confirmPublish, setConfirmPublish] = useState(false); const [mediaTarget, setMediaTarget] = useState<string | null>(null); const previewRef = useRef<HTMLIFrameElement>(null); const draftRef = useRef(draft); draftRef.current = draft;
  const load = useCallback(async () => { const data = await adminApi.document(documentKey); setRecord(data); setDraft(hydrateCmsDocument(documentKey, data.draft)); setDirty(false); setSaveState('idle'); }, [documentKey]);
  useEffect(() => { load().catch((error) => setToast(error.message)); }, [load]);
  const sendPreview = useCallback(() => previewRef.current?.contentWindow?.postMessage({ type: 'joozz-cms-preview', key: documentKey, document: draftRef.current }, window.location.origin), [documentKey]);
  useEffect(() => { sendPreview(); }, [draft, sendPreview]);
  useEffect(() => { const listener = (event: MessageEvent) => { if (event.origin === window.location.origin && event.data?.type === 'joozz-preview-ready') sendPreview(); }; window.addEventListener('message', listener); return () => window.removeEventListener('message', listener); }, [sendPreview]);
  useEffect(() => { if (!dirty) return; const timer = window.setTimeout(async () => { setSaveState('saving'); try { await adminApi.saveDraft(documentKey, draftRef.current); setDirty(false); setSaveState('saved'); onRefresh(); } catch (error) { setSaveState('error'); setToast(error instanceof Error ? error.message : 'Draft could not be saved.'); } }, 1800); return () => window.clearTimeout(timer); }, [dirty, documentKey, onRefresh]);
  useEffect(() => { const protect = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', protect); return () => window.removeEventListener('beforeunload', protect); }, [dirty]);
  const update = (path: string, value: unknown) => { setDraft((current) => setValue(current, path, value)); setDirty(true); setSaveState('idle'); };
  const openSection = (key: string) => { window.history.pushState({}, '', `/admin/content/${documentKey}/${key}`); setActiveSection(key); };
  const closeSection = () => { window.history.pushState({}, '', `/admin/content/${documentKey}`); setActiveSection(null); };
  const saveNow = async () => { setSaveState('saving'); try { await adminApi.saveDraft(documentKey, draftRef.current); setDirty(false); setSaveState('saved'); setToast('Draft saved. Your live website is unchanged.'); onRefresh(); } catch (error) { setSaveState('error'); setToast(error instanceof Error ? error.message : 'Draft could not be saved.'); } };
  const publish = async () => { setConfirmPublish(false); try { if (dirty) await adminApi.saveDraft(documentKey, draftRef.current); await adminApi.publish(documentKey); announcePublishedContent(documentKey); await load(); onRefresh(); setToast('Published. Open website tabs have been refreshed.'); } catch (error) { setToast(error instanceof Error ? error.message : 'Changes could not be published.'); } };
  const restore = async (id: number) => { try { const result = await adminApi.restore(documentKey, id); setDraft(hydrateCmsDocument(documentKey, result.draft)); setDirty(false); setRecord((current) => current ? { ...current, status: 'draft' } : current); onRefresh(); setToast('Revision restored as a draft. Review it before publishing.'); } catch (error) { setToast(error instanceof Error ? error.message : 'Revision could not be restored.'); } };
  if (!record) return <div className="cms-page cms-loading"><span className="cms-spinner" />Loading page content…</div>;
  const section = schema.sections.find((item) => item.key === activeSection);
  return <div className="cms-editor-page">
    <header className="cms-editor-header"><div><button className="cms-back" onClick={() => activeSection ? closeSection() : onBack()}><ArrowLeft />{activeSection ? schema.title : 'Website Content'}</button><p className="cms-breadcrumb">Website Content <span>›</span> {schema.title}{section && <><span>›</span>{section.title}</>}</p><h1>{section?.title || schema.title}</h1><p>{section?.description || schema.description}</p></div><div className="cms-editor-actions"><a href={schema.route} target="_blank" rel="noreferrer" className="cms-secondary"><ExternalLink />View live page</a></div></header>
    <div className="cms-status-row"><span className={`cms-status ${record.status}`}>{record.status === 'draft' ? 'Draft changes pending' : 'Published'}</span><span>{saveState === 'saving' ? 'Saving…' : saveState === 'saved' ? 'Draft saved' : dirty ? 'Unsaved changes' : `Last published: ${formatDate(record.publishedAt)}`}</span></div>
    {!section ? <PageSections schema={schema} draft={draft} onEdit={setActiveSection} record={record} onRestore={restore} /> : <div className="cms-workspace"><section className="cms-form-panel"><SectionEditor section={section} document={draft} documentKey={documentKey} availablePortfolio={availablePortfolio} availableServices={availableServices} update={update} chooseMedia={setMediaTarget} /></section><section className="cms-preview-panel"><div className="cms-preview-toolbar"><strong>Live website preview</strong><div><button className={device === 'desktop' ? 'active' : ''} onClick={() => setDevice('desktop')} title="Desktop"><Monitor /></button><button className={device === 'tablet' ? 'active' : ''} onClick={() => setDevice('tablet')} title="Tablet"><Tablet /></button><button className={device === 'mobile' ? 'active' : ''} onClick={() => setDevice('mobile')} title="Mobile"><Smartphone /></button><button onClick={sendPreview} title="Refresh preview"><RefreshCw /></button></div></div><div className={`cms-preview-frame ${device}`}><iframe ref={previewRef} src={`${schema.route}${schema.route.includes('?') ? '&' : '?'}cmsPreview=1`} title={`${schema.title} live preview`} onLoad={sendPreview} /></div></section></div>}
    <div className="cms-publish-bar"><div><span className={dirty ? 'dirty' : ''} />{saveState === 'saving' ? 'Saving draft…' : dirty ? 'Unsaved changes' : record.status === 'draft' ? 'Draft saved — not live yet' : 'Everything is published'}</div><div><button className="cms-secondary" onClick={saveNow}><Save />Save Draft</button><button className="cms-primary" onClick={() => setConfirmPublish(true)}><Globe2 />Publish Changes</button></div></div>
    {mediaTarget && <MediaPicker onClose={() => setMediaTarget(null)} onSelect={(url) => { update(mediaTarget, url); setMediaTarget(null); }} />}
    {confirmPublish && <ConfirmDialog title={`Publish ${schema.title}?`} description="Your saved draft will replace the content currently visible on the live website." confirm="Publish changes" onCancel={() => setConfirmPublish(false)} onConfirm={publish} />}
    {toast && <Toast message={toast} close={() => setToast('')} />}
  </div>;
}

function PageSections({ schema, draft, onEdit, record, onRestore }: { schema: DocumentSchema; draft: Record<string, unknown>; onEdit: (key: string) => void; record: CmsDocument; onRestore: (id: number) => void }) {
  const [historyOpen, setHistoryOpen] = useState(false);
  return <div className="cms-page cms-sections-page"><div className="cms-section-title"><div><p className="cms-kicker">PAGE SECTIONS</p><h2>Choose what to edit</h2><p>Content is grouped exactly as visitors see it on the website.</p></div><button className="cms-secondary" onClick={() => setHistoryOpen((value) => !value)}><Clock3 />Revision history</button></div>
    {historyOpen && <div className="cms-history"><h3>Recent published versions</h3>{record.revisions.length ? record.revisions.map((revision) => <div key={revision.id}><span><strong>{formatDate(revision.createdAt)}</strong><small>{revision.author || 'Administrator'} · {revision.action}</small></span><button className="cms-secondary" onClick={() => onRestore(revision.id)}>Restore as draft</button></div>) : <p>No previous published revisions yet.</p>}</div>}
    <div className="cms-section-grid">{schema.sections.map((section, index) => { const visible = section.visibilityPath ? getValue(draft, section.visibilityPath) !== false : true; return <button key={section.key} onClick={() => onEdit(section.key)}><span className="cms-section-number">{String(index + 1).padStart(2, '0')}</span><div><strong>{section.title}</strong><p>{section.description}</p><small className={visible ? 'visible' : 'hidden'}>{section.visibilityPath ? (visible ? 'Visible' : 'Hidden') : 'Editable'}</small></div><ExternalLink /></button>; })}</div>
  </div>;
}

function SectionEditor({ section, document, documentKey, availablePortfolio, availableServices, update, chooseMedia }: { section: SectionSchema; document: Record<string, unknown>; documentKey: string; availablePortfolio: PortfolioItem[]; availableServices: ServiceItem[]; update: (path: string, value: unknown) => void; chooseMedia: (path: string) => void }) {
  const documentCategories = getValue(document, 'categories');
  const sharedCategories = getValue(document, 'collections.categories');
  const categoryOptions = (Array.isArray(documentCategories) ? documentCategories as string[] : Array.isArray(sharedCategories) ? sharedCategories as string[] : PORTFOLIO_CATEGORIES).filter(Boolean).map((category) => ({ label: category, value: category }));
  return <div className="cms-section-editor">{section.visibilityPath && <div className="cms-visibility"><div><strong>Show this section</strong><span>Hide it without deleting its content.</span></div><Toggle value={getValue(document, section.visibilityPath) !== false} onChange={(value) => update(section.visibilityPath!, value)} /></div>}
    {section.fields?.length ? <div className="cms-field-group"><h3>Content</h3>{section.fields.map((field) => <FieldControl key={field.path} field={field} value={getValue(document, field.path)} portfolioItems={availablePortfolio} serviceItems={availableServices} section={documentKey} onChange={(value) => update(field.path, value)} chooseMedia={() => chooseMedia(field.path)} />)}</div> : null}
    {section.repeater && <RepeaterEditor schema={section.repeater} items={(getValue(document, section.repeater.path) as Record<string, unknown>[]) || []} categoryOptions={categoryOptions} onChange={(items) => update(section.repeater!.path, items)} chooseMedia={(path) => chooseMedia(`${section.repeater!.path}.${path}`)} />}
  </div>;
}

function FieldControl({ field, value, portfolioItems, serviceItems, section = 'general', onChange, chooseMedia }: { field: FieldSchema; value: unknown; portfolioItems?: PortfolioItem[]; serviceItems?: ServiceItem[]; section?: string; onChange: (value: unknown) => void; chooseMedia: () => void }) {
  const [uploading, setUploading] = useState(false);
  if (field.type === 'toggle') return <div className="cms-toggle-field"><div><strong>{field.label}</strong>{field.help && <span>{field.help}</span>}</div><Toggle value={value !== false} onChange={onChange} /></div>;
  if (field.type === 'objectList') return <ObjectListField field={field} value={Array.isArray(value) ? value as Record<string, unknown>[] : []} onChange={onChange} chooseMedia={chooseMedia} />;
  if (field.type === 'categoryList') return <CategoryListField field={field} value={Array.isArray(value) ? value as string[] : []} onChange={onChange} />;
  if (field.type === 'portfolioSelect') return <PortfolioSelectField value={Array.isArray(value) ? value as string[] : []} items={portfolioItems || []} onChange={onChange} />;
  if (field.type === 'serviceSelect') return <ServiceSelectField value={Array.isArray(value) ? value as string[] : []} items={serviceItems || CORE_SERVICES} onChange={onChange} />;
  if (field.type === 'image') {
    const url = String(value || ''); const upload = async (file?: File) => { if (!file) return; setUploading(true); try { const result = await adminApi.upload(file, field.label, section); onChange(result.url); } finally { setUploading(false); } };
    return <div className="cms-image-field"><div className="cms-field-label"><strong>{field.label}</strong>{field.help && <span>{field.help}</span>}</div><div className="cms-image-preview">{url ? (url.match(/\.(mp4|webm)(\?|$)/i) ? <video src={url} muted /> : <img src={url} alt="" />) : <div><ImageIcon /><span>No media selected</span></div>}</div><div className="cms-image-actions"><label className="cms-secondary"><Upload />{uploading ? 'Uploading…' : url ? 'Replace file' : 'Upload file'}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" onChange={(event) => upload(event.target.files?.[0])} disabled={uploading} /></label><button className="cms-secondary" type="button" onClick={chooseMedia}><ImageIcon />Media library</button>{url && <button className="cms-icon-danger" type="button" onClick={() => onChange('')} title="Remove"><Trash2 /></button>}</div></div>;
  }
  if (field.type === 'list') return <ListField field={field} value={Array.isArray(value) ? value as string[] : []} onChange={onChange} />;
  if (field.type === 'select') return <label className="cms-field cms-field-select"><span><strong>{field.label}</strong>{field.help && <small>{field.help}</small>}</span><select value={String(value || field.options?.[0]?.value || '')} onChange={(event) => onChange(event.target.value)}>{field.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
  const common = { value: value == null ? '' : String(value), onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(field.type === 'number' ? Number(event.target.value) : event.target.value), placeholder: field.placeholder };
  return <label className={`cms-field ${field.type === 'textarea' ? 'cms-field-wide' : ''}`}><span><strong>{field.label}</strong>{field.help && <small>{field.help}</small>}</span>{field.type === 'textarea' ? <textarea rows={5} {...common} /> : <input type={field.type === 'url' ? 'text' : field.type === 'number' ? 'number' : 'text'} {...common} />}</label>;
}

function ListField({ field, value, onChange }: { field: FieldSchema; value: string[]; onChange: (value: unknown) => void }) {
  const serializedValue = value.join('\n');
  const [text, setText] = useState(serializedValue);
  const normalize = (nextText: string) => nextText.split(/\r?\n/).map((item) => item.trim()).filter(Boolean);

  // Keep an unfinished trailing line in the textarea. Previously, pressing Enter
  // immediately removed that empty line when the list value was normalized.
  useEffect(() => {
    if (serializedValue !== normalize(text).join('\n')) setText(serializedValue);
  }, [serializedValue, text]);

  return <label className="cms-field cms-field-wide"><span><strong>{field.label}</strong>{field.help && <small>{field.help}</small>}</span><textarea rows={5} value={text} onChange={(event) => { const nextText = event.target.value; setText(nextText); onChange(normalize(nextText)); }} onBlur={() => setText(normalize(text).join('\n'))} placeholder={field.placeholder} /></label>;
}

function PortfolioSelectField({ value, items, onChange }: { value: string[]; items: PortfolioItem[]; onChange: (value: unknown) => void }) {
  const selected = new Set(value);
  const toggle = (id: string) => { const next = new Set(selected); if (next.has(id)) next.delete(id); else next.add(id); onChange(items.filter((item) => next.has(item.id)).map((item) => item.id)); };
  return <div className="cms-portfolio-select"><div className="cms-field-label"><strong>Featured Works</strong><span>Select the projects to show on the Home page. Their content stays managed in Portfolio.</span></div>{items.length ? <div className="cms-portfolio-options">{items.map((item) => <label key={item.id} className={selected.has(item.id) ? 'selected' : ''}><input type="checkbox" checked={selected.has(item.id)} onChange={() => toggle(item.id)} /><span>{item.title}</span><small>{item.category}</small></label>)}</div> : <div className="cms-empty"><span>No portfolio projects are available yet.</span></div>}<small className="cms-selection-count">{selected.size} selected</small></div>;
}

function ServiceSelectField({ value, items, onChange }: { value: string[]; items: ServiceItem[]; onChange: (value: unknown) => void }) {
  // Earlier drafts used the legacy ID. Keep those selections working while
  // saving all new choices with the database's canonical service ID.
  const selected = new Set(value.map((id) => id === 'branding-marketing' ? 'branding-marketing-design' : id));
  const toggle = (id: string) => { const next = new Set(selected); if (next.has(id)) next.delete(id); else next.add(id); onChange(items.filter((item) => next.has(item.id)).map((item) => item.id)); };
  return <div className="cms-portfolio-select"><div className="cms-field-label"><strong>Featured Services</strong><span>Choose the services shown in this Home page section.</span></div><div className="cms-portfolio-options">{items.filter((item) => item.visible !== false).map((item) => <label key={item.id} className={selected.has(item.id) ? 'selected' : ''}><input type="checkbox" checked={selected.has(item.id)} onChange={() => toggle(item.id)} /><span>{item.title}</span><small>{item.tagline}</small></label>)}</div><small className="cms-selection-count">{selected.size} selected</small></div>;
}

function ObjectListField({ field, value, onChange, chooseMedia }: { field: FieldSchema; value: Record<string, unknown>[]; onChange: (value: unknown) => void; chooseMedia: () => void }) {
  const updateItem = (index: number, path: string, nextValue: unknown) => { const next = clone(value); next[index] = setValue(next[index] || {}, path, nextValue); onChange(next); };
  return <div className="cms-object-list"><div className="cms-field-label"><strong>{field.label}</strong>{field.help && <span>{field.help}</span>}</div>{value.map((item, index) => <article key={index}><header><strong>{String(item.title || item.name || `${field.label} ${index + 1}`)}</strong><div><button onClick={() => { if (index > 0) { const next = clone(value); [next[index - 1], next[index]] = [next[index], next[index - 1]]; onChange(next); } }} disabled={index === 0}><ChevronUp /></button><button onClick={() => { if (index < value.length - 1) { const next = clone(value); [next[index + 1], next[index]] = [next[index], next[index + 1]]; onChange(next); } }} disabled={index === value.length - 1}><ChevronDown /></button><button className="danger" onClick={() => onChange(value.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></button></div></header>{field.fields?.map((child) => <FieldControl key={child.path} field={child} value={getValue(item, child.path)} onChange={(nextValue) => updateItem(index, child.path, nextValue)} chooseMedia={chooseMedia} />)}</article>)}<button className="cms-add" type="button" onClick={() => onChange([...value, {}])}><Plus />Add item</button></div>;
}

function CategoryListField({ field, value, onChange }: { field: FieldSchema; value: string[]; onChange: (value: unknown) => void }) {
  return <div className="cms-category-list"><div className="cms-field-label"><strong>{field.label}</strong>{field.help && <span>{field.help}</span>}</div>{value.map((category, index) => <div className="cms-category-row" key={index}><input value={category} onChange={(event) => { const next = [...value]; next[index] = event.target.value; onChange(next); }} placeholder="Category name" /><button type="button" className="cms-icon-danger" onClick={() => onChange(value.filter((_, itemIndex) => itemIndex !== index))} title="Remove category"><Trash2 /></button></div>)}<button type="button" className="cms-add" onClick={() => onChange([...value, ''])}><Plus />Add category</button></div>;
}

function RepeaterEditor({ schema, items, categoryOptions, onChange, chooseMedia }: { schema: RepeaterSchema; items: Record<string, unknown>[]; categoryOptions: Array<{ label: string; value: string }>; onChange: (items: Record<string, unknown>[]) => void; chooseMedia: (path: string) => void }) {
  const [open, setOpen] = useState<number | null>(items.length ? 0 : null);
  const isServiceList = schema.itemName === 'Service';
  const isProjectList = schema.itemName === 'Project';
  const entries = items.map((item, index) => ({ item, index })).filter(({ item }) => !schema.filter || getValue(item, schema.filter.path) === schema.filter.value);
  const updateItem = (index: number, path: string, value: unknown) => { const next = clone(items); next[index] = setValue(next[index] || {}, path, value); if (isServiceList && path === 'title' && !next[index].id) next[index].id = String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); onChange(next); };
  const move = (index: number, direction: -1 | 1) => { const visibleIndex = entries.findIndex((entry) => entry.index === index); const target = entries[visibleIndex + direction]?.index; if (target === undefined) return; const next = clone(items); [next[index], next[target]] = [next[target], next[index]]; onChange(next); setOpen(target); };
  return <div className="cms-repeater"><div className="cms-repeater-heading"><div><h3>{schema.itemName}s</h3><p>Open an item to edit it. Use the arrows to change its order.</p></div><button className="cms-primary" type="button" onClick={() => { const newItem = isServiceList ? { visible: true, id: '', title: 'New Service', tagline: '', description: '', deliverables: [], whatWeOffer: [], idealFor: '', iconName: 'PenTool' } : isProjectList ? { visible: true, id: `new-project-${items.length + 1}`, title: 'New Project', category: '', client: '', year: String(new Date().getFullYear()), description: '', thumbnail: '', mediaUrl: '', placeholderLabel: '', deliverables: [], type: 'image', isEmbed: false } : { visible: true }; if (schema.filter) setValue(newItem, schema.filter.path, schema.filter.value); onChange([...items, newItem]); setOpen(items.length); }}><Plus />Add {schema.itemName}</button></div>{entries.length === 0 && <div className="cms-empty"><FileText /><strong>No {schema.itemName.toLowerCase()}s added yet.</strong><span>Add the first item when you are ready.</span></div>}{entries.map(({ item, index }, displayIndex) => <article className={`cms-repeat-item ${open === index ? 'open': ''}`} key={index}><header onClick={() => setOpen(open === index ? null : index)}><span className="cms-drag">{String(displayIndex + 1).padStart(2, '0')}</span><div><strong>{String(getValue(item, schema.titlePath) || `New ${schema.itemName}`)}</strong><small>{item.visible === false ? 'Hidden' : 'Visible'}</small></div><div className="cms-repeat-actions" onClick={(event) => event.stopPropagation()}><button onClick={() => move(index, -1)} disabled={displayIndex === 0}><ChevronUp /></button><button onClick={() => move(index, 1)} disabled={displayIndex === entries.length - 1}><ChevronDown /></button><button className="danger" onClick={() => { onChange(items.filter((_, itemIndex) => itemIndex !== index)); setOpen(null); }}><Trash2 /></button><button onClick={() => setOpen(open === index ? null : index)}>{open === index ? <ChevronUp /> : <ChevronDown />}</button></div></header>{open === index && <div className="cms-repeat-fields">{schema.fields.map((field) => { const currentCategory = String(getValue(item, field.path) || ''); const options = categoryOptions.some((option) => option.value === currentCategory) || !currentCategory ? categoryOptions : [{ label: `Unlisted: ${currentCategory}`, value: currentCategory }, ...categoryOptions]; const resolvedField = field.path === 'category' && options.length ? { ...field, type: 'select' as const, options, help: 'Choose a shared category managed in Global Content.' } : field; return <FieldControl key={field.path} field={resolvedField} value={getValue(item, field.path)} onChange={(value) => updateItem(index, field.path, value)} chooseMedia={() => chooseMedia(`${index}.${field.path}`)} />; })}</div>}</article>)}</div>;
}

function Toggle({ value, onChange }: { value: boolean; onChange: (value: boolean) => void }) { return <button type="button" className={`cms-switch ${value ? 'on' : ''}`} onClick={() => onChange(!value)} aria-pressed={value}><span /></button>; }

function MediaPicker({ onSelect, onClose }: { onSelect: (url: string) => void; onClose: () => void }) {
  const [items, setItems] = useState<MediaItem[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); adminApi.media(query).then(({ items: media }) => setItems(media)).finally(() => setLoading(false)); }, 250); return () => window.clearTimeout(timer); }, [query]);
  return <div className="cms-modal-backdrop"><div className="cms-media-modal"><header><div><p className="cms-kicker">MEDIA LIBRARY</p><h2>Choose a file</h2></div><button onClick={onClose}><X /></button></header><div className="cms-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search uploaded files…" /></div>{loading ? <div className="cms-loading"><span className="cms-spinner" />Loading media…</div> : <div className="cms-media-grid">{items.map((item) => <button key={item.id} onClick={() => onSelect(item.url)}>{item.type.startsWith('video/') ? <video src={item.url} muted /> : <img src={item.url} alt={item.altText} />}<span><strong>{item.name}</strong><small>{item.altText || 'No alternative text'}</small></span></button>)}</div>}</div></div>;
}

function MediaLibrary() {
  const [items, setItems] = useState<MediaItem[]>([]); const [query, setQuery] = useState(''); const [section, setSection] = useState('general'); const [loading, setLoading] = useState(true); const [toast, setToast] = useState(''); const [deleteItem, setDeleteItem] = useState<MediaItem | null>(null);
  const load = useCallback(() => { setLoading(true); adminApi.media(query).then(({ items: media }) => setItems(media)).catch((error) => setToast(error.message)).finally(() => setLoading(false)); }, [query]);
  useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer); }, [load]);
  const upload = async (file?: File) => { if (!file) return; try { await adminApi.upload(file, file.name.replace(/\.[^.]+$/, ''), section); setToast(`Media uploaded to ${section}.`); load(); } catch (error) { setToast(error instanceof Error ? error.message : 'Upload failed.'); } };
  return <div className="cms-page"><div className="cms-page-heading cms-heading-row"><div><p className="cms-kicker">ASSET LIBRARY</p><h1>Media Library</h1><p>Upload once, add helpful alternative text and keep files organised by website section.</p></div><div className="cms-media-upload-actions"><label className="cms-field cms-field-select"><span><strong>Upload to section</strong><small>New files will be stored in this folder.</small></span><select value={section} onChange={(event) => setSection(event.target.value)}><option value="general">General</option><option value="home">Home</option><option value="about">About</option><option value="services">Services</option><option value="portfolio">Portfolio</option><option value="contact">Contact</option><option value="global">Global</option><option value="team">Team</option></select></label><label className="cms-primary"><Upload />Upload media<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" onChange={(event) => upload(event.target.files?.[0])} /></label></div></div><div className="cms-search cms-content-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by filename…" /></div>{loading ? <div className="cms-loading"><span className="cms-spinner" />Loading media…</div> : items.length ? <div className="cms-library-grid">{items.map((item) => <article key={item.id}>{item.type.startsWith('video/') ? <video src={item.url} controls /> : <img src={item.url} alt={item.altText} />}<div><strong>{item.name}</strong><small>{Math.ceil(item.size / 1024)} KB · {item.type}</small><label>Alternative text<input defaultValue={item.altText} onBlur={(event) => adminApi.updateMedia(item.id, event.target.value).then(() => setToast('Alternative text saved.')).catch((error) => setToast(error.message))} /></label><div><button className="cms-secondary" onClick={() => navigator.clipboard.writeText(`${location.origin}${item.url}`).then(() => setToast('Link copied.'))}>Copy link</button><button className="cms-icon-danger" onClick={() => setDeleteItem(item)}><Trash2 /></button></div></div></article>)}</div> : <div className="cms-empty"><ImageIcon /><strong>No media found.</strong><span>Upload an image or video to start your library.</span></div>}{deleteItem && <ConfirmDialog title={`Delete “${deleteItem.name}”?`} description="The file can only be deleted when it is not being used by published or draft content." confirm="Delete media" danger onCancel={() => setDeleteItem(null)} onConfirm={() => adminApi.deleteMedia(deleteItem.id).then(() => { setDeleteItem(null); load(); setToast('Media deleted.'); }).catch((error) => { setDeleteItem(null); setToast(error.message); })} />}{toast && <Toast message={toast} close={() => setToast('')} />}</div>;
}

function Enquiries() {
  const [items, setItems] = useState<Enquiry[]>([]); const [loading, setLoading] = useState(true); const [toast, setToast] = useState(''); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('all'); const [serviceFilter, setServiceFilter] = useState('all');
  useEffect(() => { adminApi.enquiries().then(({ items: enquiries }) => setItems(enquiries)).catch((error) => setToast(error.message)).finally(() => setLoading(false)); }, []);
  const services = [...new Set([...CORE_SERVICES.filter((service) => service.visible !== false && service.title).map((service) => service.title), ...items.map((item) => item.service)].filter(Boolean))];
  const filteredItems = items.filter((item) => { const text = `${item.name} ${item.email} ${item.phone || ''} ${item.service} ${item.message}`.toLowerCase(); return (statusFilter === 'all' || item.status === statusFilter) && (serviceFilter === 'all' || item.service === serviceFilter) && text.includes(query.trim().toLowerCase()); });
  if (loading) return <div className="cms-page cms-loading"><span className="cms-spinner" />Loading enquiries…</div>;
  return <div className="cms-page"><div className="cms-page-heading"><p className="cms-kicker">PROJECT REQUESTS</p><h1>Enquiries</h1><p>Review messages and keep their follow-up status organised.</p></div>{items.length ? <><div className="cms-enquiry-filters"><div className="cms-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, service, or message" /></div><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">All statuses</option>{['new', 'read', 'replied', 'archived'].map((status) => <option key={status} value={status}>{status}</option>)}</select><select value={serviceFilter} onChange={(event) => setServiceFilter(event.target.value)}><option value="all">All services</option>{services.map((service) => <option key={service} value={service}>{service}</option>)}</select></div>{filteredItems.length ? <div className="cms-enquiries">{filteredItems.map((item) => <article key={item.id}><header><div><strong>{item.name}</strong><a href={`mailto:${item.email}`}>{item.email}</a></div><select value={item.status} onChange={(event) => { const status = event.target.value; adminApi.updateEnquiry(item.id, status).then(() => { setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, status } : entry)); setToast('Enquiry status updated.'); }).catch((error) => setToast(error.message)); }}>{['new', 'read', 'replied', 'archived'].map((status) => <option key={status}>{status}</option>)}</select></header><div className="cms-enquiry-meta"><span>{item.service}</span><span>{formatDate(item.createdAt)}</span>{item.phone && <a href={`tel:${item.phone}`}>{item.phone}</a>}</div><p>{item.message}</p></article>)}</div> : <div className="cms-empty"><Search /><strong>No enquiries match these filters.</strong><span>Change or clear a filter to see more requests.</span></div>}</> : <div className="cms-empty"><Send /><strong>No enquiries yet.</strong><span>New project requests will appear here.</span></div>}{toast && <Toast message={toast} close={() => setToast('')} />}</div>;
}

function ConfirmDialog({ title, description, confirm, danger, onConfirm, onCancel }: { title: string; description: string; confirm: string; danger?: boolean; onConfirm: () => void; onCancel: () => void }) { return <div className="cms-modal-backdrop"><div className="cms-confirm"><div className={danger ? 'danger' : ''}>{danger ? <Trash2 /> : <Globe2 />}</div><h2>{title}</h2><p>{description}</p><footer><button className="cms-secondary" onClick={onCancel}>Cancel</button><button className={danger ? 'cms-danger' : 'cms-primary'} onClick={onConfirm}>{confirm}</button></footer></div></div>; }
function Toast({ message, close }: { message: string; close: () => void }) { useEffect(() => { const timer = window.setTimeout(close, 4000); return () => window.clearTimeout(timer); }, [close]); return <div className="cms-toast"><Check />{message}<button onClick={close}><X /></button></div>; }
